#!/usr/bin/perl

while (<>) 
{
    $a=$_;
    if ($a=~/([Ii]ncorrect)|([Ee]rror)|(while)/)
    { 
	print "<span class=\"red\"><b>!!! Here is the error !!!</b>\n".$a."</span>";
    }
    else 
    {
	print $a;
    }
}

print "\n";
